train:
        batch_size: 64
        epochs: 100
        optimizer: 'adam'
        drop_remainder: True
        len_dataset: 13100


encoder:
        char_embedding_size: 512

        conv_layer:
                n: 3
                filter : 5
                kernel_size : [3]
                dropout_rate: 0.5
        bi_lstm:
                units: 256

decoder:
        prenet:
                n: 2
                units: 256
                dropout_rate: 0.5
        lsattention:
                rnn_dim: 512
                embed_dim: 512
                att_dim: 128
                att_n_filters: 32
                att_ker_size: 31
        
        dec_rnn_units: 1024 

        char_embedding_size: 512

        postnet:
                filters: 512
                n: 5
                kernel_size: 31
                dropout_rate: 0.1


n_mel_channels: 80
n_frames_per_step: 1

train_data:
        transcript_path: "/gpfswork/rech/xcz/ukv19jy/mine/tacotron2/preprocess/metadata_pp.csv"
        audio_dir: "/gpfswork/rech/xcz/ukv19jy/tacotron2/LJSpeech-1.1/wavs"
        statistics: "/gpfswork/rech/xcz/ukv19jy/mine/tacotron2/preprocess/ljspeech_stats.csv"
        checkpoint_path: "/gpfswork/rech/xcz/ukv19jy/mine/tacotron2/checkpoint/"

mel_spec:
        frame_length: 1024
        frame_step: 256
        fft_length: None
        sampling_rate: 22050
        n_mel_channels: 80
        freq_min: 125
        freq_max: 7600
