train:
        batch_size: 32
        epochs: 100
        optimizer: 'adam'
        drop_remainder: True
        len_dataset: 13100


encoder:
        char_embedding_size: 512

        conv_layer:
                n: 3
                filter : 5
                kernel_size : [3]
                dropout_rate: 0.5
        bi_lstm:
                units: 128

decoder:
        prenet:
                n: 2
                units: 256
                dropout_rate: 0.5
        lsattention:
                rnn_dim: 512
                embed_dim: 512
                att_dim: 128
                att_n_filters: 32
                att_ker_size: 31
        
        dec_rnn_units: 256 

        char_embedding_size: 512

        postnet:
                filters: 32
                n: 5
                kernel_size: 31
                dropout_rate: 0.5


n_mel_channels: 80
n_frames_per_step: 10

train_data:
        transcript_path: "/data/anasynth_nonbp/lemerle/mytacotron/tacotron2/preprocess/metadata_pp.csv"
        audio_dir: "/data/anasynth_nonbp/lemerle/TTS/LJSpeech-1.1/wavs"

mel_spec:
        frame_length: 1024
        frame_step: 256
        fft_length: None
        sampling_rate: 22050
        n_mel_channels: 80
        freq_min: 125
        freq_max: 7600
