batch_size: 32
epochs: 100
optimizer: 'adam'
drop_remainder: True
len_dataset: 13100
clip_norm: 1.0

data:
        transcript_path: "preprocess/metadata_pp.csv"
        audio_dir: "/home/theodor/LJSpeech-1.1/wavs"
        statistics: "/home/theodor/ircam_tts/preprocess/ljspeech_stats.csv"
        checkpoint_path: "/home/theodor/ircam_tts/checkpoint/"
